#!/bin/bash
#PBS -l nodes=1:ppn=16:xk
#PBS -l walltime=12:00:00
#PBS -N RL_Cont_Control
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
#PBS -q normal
#PBS -m bea
#PBS -M sbhadur2@illinois.edu

cd ~/scratch/HW7

. /opt/modules/default/init/bash # NEEDED to add module commands to shell
module swap PrgEnv-cray PrgEnv-gnu
module load bwpy
module load bwpy-mpi
module load tensorflow
module load cudatoolkit

alias python='python3.4'
export CPATH="${BWPY_INCLUDE_PATH}"
export LIBRARY_PATH="${BWPY_LIBRARY_PATH}"
export PMI_NO_FORK=1
export PMI_NO_PREINITIALIZE=1

aprun -n 1 -d 16 -cc none python3.4 GA3C.py >& $PBS_JOBID.log
